all :
	/Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_strcpy.s
	/Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_strlen.s
	/Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_strcmp.s
	/Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_write.s
	/Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_read.s
	/Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_strdup.s
	# nasm -f macho64 ./ft_strlen.s
	# nasm -f macho64 ./ft_strlen.s
	# nasm -f macho64 ./ft_strcmp.s
	gcc main.c ft_strlen.o ft_strcpy.o ft_strcmp.o ft_write.o ft_read.o ft_strdup.o
	./a.out
	