all :
	# /Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_strcpy.s
	# /Users/htumanya/Downloads/nasm-2.15.05/nasm -f macho64 ./ft_strlen.s
	nasm -f macho64 ./ft_strlen.s
	nasm -f macho64 ./ft_strlen.s
	nasm -f macho64 ./ft_strcmp.s
	gcc main.c ft_strlen.o ft_strcpy.o ft_strcmp.o
	./a.out
	